[workspace]
members = [
  "v-api",
  "v-api-installer", "v-api-permission-derive",
  "v-model",
]
resolver = "2"

[workspace.dependencies]
async-bb8-diesel = { git = "https://github.com/oxidecomputer/async-bb8-diesel" }
async-trait = "0.1.79"
base64 = "0.21.7"
bb8 = "0.8.3"
chrono = "0.4.37"
config = { version = "0.13.4", features = ["toml"] }
cookie = { version = "0.18.1" }
crc32c = "0.6.5"
diesel = { version = "2.1.5", features = ["postgres"] }
diesel_migrations = { version = "2.1.0" }
dropshot = "0.10.0"
dropshot-verified-body = { git = "https://github.com/oxidecomputer/dropshot-verified-body" }
google-cloudkms1 = "5.0.4"
heck = "0.5.0"
hex = "0.4.3"
http = "0.2.12"
hyper = "0.14.28"
hyper-rustls = "0.24.2"
jsonwebtoken = "9.2.0"
mockall = "0.12.1"
newtype-uuid = { version = "1.0.1", features = ["schemars08", "serde", "v4"] }
oauth2 = "4.4.2"
partial-struct = { git = "https://github.com/oxidecomputer/partial-struct" }
proc-macro2 = "1"
quote = "1"
rand = "0.8.5"
rand_core = "0.6"
regex = "1.10.4"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream"] }
ring = "0.17.8"
rsa = "0.9.6"
schemars = "0.8.16"
secrecy = "0.8.0"
serde = "1"
serde_bytes = "0.11.14"
serde_json = "1"
serde_urlencoded = "0.7.1"
sha2 = "0.10.8"
slog = "2.7.0"
slog-async = "2.8.0"
syn = "1"
tap = "1.0.1"
thiserror = "1.0.56"
tokio = "1.37.0"
toml = "0.8.8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-bunyan-formatter = "0.3.9"
tracing-core = "0.1.32"
tracing-slog = { git = "https://github.com/oxidecomputer/tracing-slog" }
tracing-subscriber = "0.3.18"
uuid = "1.6.1"
valuable = "0.1.0"
yup-oauth2 = "8.3.0"
